version: '3'

services:
  task-app-frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: task-app-frontend
    container_name: task-app-frontend
    restart: unless-stopped
    ports:
      - "5003:80"
    networks:
      - task-network
networks:
  task-network:
    driver: bridge
    external: true